/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author kms03
 */
public class InputDialog extends javax.swing.JFrame {

    DB_MAN DBM = new DB_MAN();
    private String currentUserId;
    private MainFrame mainFrame; // 메인 프레임 참조 변수
    
    // 수정할 글 번호 (0: 신규 등록, 그 외: 해당 번호 수정)
    private int editRecordNo = 0;

    public InputDialog(MainFrame mainFrame, String userId) {
        initComponents(); // NetBeans 자동 생성 코드 초기화
        
        this.mainFrame = mainFrame;
        this.currentUserId = userId;
        
        this.setTitle("내역 추가");
        this.setLocationRelativeTo(null); // 화면 중앙 배치
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // 날짜 초기값 설정 (오늘)
        txtDate.setText(LocalDate.now().toString());
        rbtExpense.setSelected(true); // 기본값: 지출
        updateCategories(); // 카테고리 목록 로드
    }
    
    // 기본 생성자
    public InputDialog() {
        initComponents();
    }

    
    // 수정 모드 데이터 설정 메서드
    public void setEditData(int no, String date, String type, String category, int amount, String memo) {
        this.editRecordNo = no; // 수정할 레코드 번호 저장
        
        // 기존 데이터 UI에 바인딩
        txtDate.setText(date);
        if (type.equals("수입")) rbtIncome.setSelected(true);
        else rbtExpense.setSelected(true);
        
        updateCategories(); // 카테고리 목록 갱신
        cboCategory.setSelectedItem(category);
        
        txtAmount.setText(String.valueOf(amount));
        txtMemo.setText(memo);
        
        btnSave.setText("수정 완료"); // 버튼 텍스트 변경
        this.setTitle("내역 수정");
    }

    // 수입/지출 선택에 따른 카테고리 갱신
    private void updateCategories() {
        String[] items;
        if (rbtIncome.isSelected()) {
            items = new String[]{"월급", "용돈", "보너스", "부수입", "금융수입", "기타"};
        } else {
            items = new String[]{"식비", "교통비", "쇼핑", "문화생활", "주거/통신", "의료/건강", "교육", "경조사", "저축", "기타"};
        }
        // 콤보박스 모델 재설정
        cboCategory.setModel(new DefaultComboBoxModel<>(items));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtDate = new javax.swing.JLabel();
        rbtIncome = new javax.swing.JRadioButton();
        rbtExpense = new javax.swing.JRadioButton();
        cboCategory = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        txtMemo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDate.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        txtDate.setText("2025-11-26");

        buttonGroup1.add(rbtIncome);
        rbtIncome.setText("수입");
        rbtIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtIncomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtExpense);
        rbtExpense.setText("지출");
        rbtExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtExpenseActionPerformed(evt);
            }
        });

        btnSave.setText("저장");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("닫기");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel1.setText("구분");

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel2.setText("카테고리");

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel3.setText("금액");

        jLabel4.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        jLabel4.setText("메모");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtIncome)
                                .addGap(12, 12, 12)
                                .addComponent(rbtExpense))
                            .addComponent(jLabel2)
                            .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtDate)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtIncome)
                    .addComponent(rbtExpense))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(txtMemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // 입력값 가져오기
        String date = txtDate.getText().trim();
        String category = cboCategory.getSelectedItem().toString();
        String amountStr = txtAmount.getText().trim();
        String memo = txtMemo.getText().trim();
        String type = rbtIncome.isSelected() ? "수입" : "지출";

        // 필수 입력 확인
        if (date.isEmpty() || amountStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "날짜와 금액은 필수입니다."); return;
        }

        // 금액 숫자 변환 및 검증
        int amount = 0;
        try {
            amount = Integer.parseInt(amountStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "금액은 숫자만 입력해주세요."); return;
        }

        // 쿼리 생성 (신규 or 수정)
        String sql;
        if (editRecordNo == 0) { // 신규 등록
            sql = String.format("INSERT INTO account_book (user_id, t_date, t_type, category, amount, memo) " +
                                "VALUES ('%s', '%s', '%s', '%s', %d, '%s')",
                                currentUserId, date, type, category, amount, memo);
        } else { // 기존 내역 수정
            sql = String.format("UPDATE account_book SET t_date='%s', t_type='%s', category='%s', amount=%d, memo='%s' " +
                                "WHERE no=%d",
                                date, type, category, amount, memo, editRecordNo);
        }

        try {
            DBM.dbOpen(); // DB 연결
            DBM.DB_stmt.executeUpdate(sql); // 쿼리 실행
            
            String msg = (editRecordNo == 0) ? "저장되었습니다!" : "수정되었습니다!";
            JOptionPane.showMessageDialog(this, msg);
            
            // 메인 프레임 데이터 갱신
            if (mainFrame != null) {
                mainFrame.updateSummary();       
                mainFrame.loadTransactionList(); 
            }
            this.dispose(); // 창 닫기
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DB 오류: " + e.getMessage());
        } finally {
            try { DBM.dbClose(); } catch (IOException e) {}
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void rbtIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtIncomeActionPerformed
        updateCategories();
    }//GEN-LAST:event_rbtIncomeActionPerformed

    private void rbtExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtExpenseActionPerformed
        updateCategories();
    }//GEN-LAST:event_rbtExpenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtExpense;
    private javax.swing.JRadioButton rbtIncome;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtMemo;
    // End of variables declaration//GEN-END:variables
}
