/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author kms03
 */
public class JoinFrame extends javax.swing.JFrame {

    // 1. 클래스 멤버 변수 선언
    DB_MAN DBM = new DB_MAN();
    private String correctCaptchaAnswer = ""; // 캡차 정답 저장 변수
    
    // ID 중복 확인 상태 (0: 미확인, 1: 사용 가능, 2: 사용 불가)
    private int idCheckStatus = 0; 
    
    // 생성자
    public JoinFrame() {
        initComponents();
        this.setTitle("시크릿 자산 관리부 - 회원가입");
        this.setLocationRelativeTo(null); // 화면 중앙 배치
        
        // 초기 설정 실행
        setupSecurityQuestions();
        loadCaptcha(); 
    }
    
    // 캡차 생성 및 화면 표시 메서드
    private void loadCaptcha() {
        CaptchaGenerator generator = new CaptchaGenerator();
        
        correctCaptchaAnswer = generator.getCaptchaText(); // 정답 텍스트 확보
        BufferedImage img = generator.getCaptchaImage();   // 이미지 확보
        
        lblCaptchaImage.setIcon(new ImageIcon(img)); // 라벨에 이미지 설정
        txtCaptchaInput.setText(""); // 입력 필드 초기화
    }
    
    // 보안 질문 콤보박스 설정 메서드
    private void setupSecurityQuestions() {
        String[] questions = {
            "어릴 적 살던 동네 이름은?",
            "가장 좋아하는 음식 이름은?",
            "가장 아끼는 반려동물의 이름은?",
            "가장 기억에 남는 선생님 이름은?",
            "졸업한 초등학교의 이름은?",      
            "가장 감명 깊게 본 영화 제목은?", 
            "가장 가고 싶은 여행지는?",      
            "어릴 적 나의 별명은?",          
            "나의 보물 1호는 무엇인가요?"     
        };
        cboQuestion.setModel(new DefaultComboBoxModel<>(questions));
        cboQuestion.setSelectedIndex(0); // 첫 번째 항목 기본 선택
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPWCheck = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        lblAnwer = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnIDCheck = new javax.swing.JButton();
        txtPW = new javax.swing.JPasswordField();
        txtPWConfirm = new javax.swing.JPasswordField();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        lblCaptchaImage = new javax.swing.JLabel();
        txtCaptchaInput = new javax.swing.JTextField();
        btnReloadCaptcha = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cboQuestion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("회원가입");

        lblPW.setText("비밀번호");

        lblID.setText("아이디");

        lblName.setText("이름");

        lblPWCheck.setText("비밀번호 확인");

        lblPhone.setText("전화번호");

        lblQuestion.setText("보안 질문");

        lblAnwer.setText("정답");

        btnIDCheck.setText("중복확인");
        btnIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDCheckActionPerformed(evt);
            }
        });

        btnReloadCaptcha.setText("새로고침");
        btnReloadCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadCaptchaActionPerformed(evt);
            }
        });

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        btnCancel.setText("닫기");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("자동 가입 방지 이미지");

        jLabel2.setText("이미지를 보이는 대로 입력하세요.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhone)
                            .addComponent(lblAnwer)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPWCheck)
                                    .addComponent(lblName)
                                    .addComponent(lblQuestion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName)
                                    .addComponent(txtPWConfirm)
                                    .addComponent(txtPhone)
                                    .addComponent(txtAnswer)
                                    .addComponent(cboQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblCaptchaImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCaptchaInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblID)
                                                .addComponent(lblPW))
                                            .addGap(47, 47, 47)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtID)
                                                .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnReloadCaptcha))
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIDCheck)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnJoin)))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW)
                    .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPWCheck)
                    .addComponent(txtPWConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuestion)
                    .addComponent(cboQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnwer)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReloadCaptcha)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCaptchaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJoin)
                    .addComponent(txtCaptchaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadCaptchaActionPerformed
        loadCaptcha();
    }//GEN-LAST:event_btnReloadCaptchaActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDCheckActionPerformed
        String inputId = txtID.getText().trim();
        
        // 입력값 확인
        if (inputId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력해주세요.", "경고", JOptionPane.WARNING_MESSAGE);
            idCheckStatus = 0;
            return;
        }
        
        String strSQL = "SELECT id FROM member WHERE id = '" + inputId + "'";

        try {
            DBM.dbOpen(); // DB 연결
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);

            if (DBM.DB_rs.next()) {
                // 이미 존재함
                JOptionPane.showMessageDialog(this, "'" + inputId + "'은(는) 이미 사용 중인 아이디입니다.", "중복", JOptionPane.WARNING_MESSAGE);
                idCheckStatus = 2; // 사용 불가
            } else {
                // 사용 가능
                JOptionPane.showMessageDialog(this, "'" + inputId + "'은(는) 사용 가능한 아이디입니다.", "사용 가능", JOptionPane.INFORMATION_MESSAGE);
                idCheckStatus = 1; // 사용 가능
            }

            DBM.DB_rs.close();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "DB 연결 오류가 발생했습니다.", "시스템 오류", JOptionPane.ERROR_MESSAGE);
            idCheckStatus = 0;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ID 중복 확인 중 오류 발생: " + e.getMessage(), "시스템 오류", JOptionPane.ERROR_MESSAGE);
            idCheckStatus = 0;
        } finally {
            try { DBM.dbClose(); } catch (IOException e) { /* 무시 */ }
        }
    }//GEN-LAST:event_btnIDCheckActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // 입력값 가져오기
        String id = txtID.getText().trim();
        String pw = new String(txtPW.getPassword());
        String pwConfirm = new String(txtPWConfirm.getPassword());
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String question = cboQuestion.getSelectedItem().toString();
        String answer = txtAnswer.getText().trim();
        String captchaInput = txtCaptchaInput.getText().trim();

        // 1. 필수 항목 입력 확인
        if (id.isEmpty() || pw.isEmpty() || pwConfirm.isEmpty() || name.isEmpty() || phone.isEmpty() || answer.isEmpty() || captchaInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "모든 항목을 입력해주세요.", "경고", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. ID 중복 확인 여부 검사
        if (idCheckStatus != 1) {
            JOptionPane.showMessageDialog(this, "아이디 중복 확인이 필요합니다.", "경고", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. 비밀번호 일치 확인
        if (!pw.equals(pwConfirm)) {
            JOptionPane.showMessageDialog(this, "비밀번호가 일치하지 않습니다.", "경고", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 4. 캡차 정답 확인 (대소문자 무시)
        if (!captchaInput.equalsIgnoreCase(correctCaptchaAnswer)) {
            JOptionPane.showMessageDialog(this, "CAPTCHA 입력이 틀렸습니다. 다시 시도해 주세요.", "경고", JOptionPane.WARNING_MESSAGE);
            loadCaptcha(); // 실패 시 캡차 새로고침
            return;
        }

        // 5. 회원 정보 DB 삽입
        String strSQL = String.format("INSERT INTO member VALUES ('%s', '%s', '%s', '%s', '%s', '%s')", 
                                      id, pw, name, phone, question, answer);

        try {
            DBM.dbOpen();
            int result = DBM.DB_stmt.executeUpdate(strSQL);
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "회원가입이 완료되었습니다!\n로그인 해주세요.", "성공", JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); // 창 닫기
            } else {
                 JOptionPane.showMessageDialog(this, "회원가입에 실패했습니다.", "오류", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "DB 삽입 오류: " + e.getMessage(), "오류", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try { DBM.dbClose(); } catch (IOException e) { /* 무시 */ }
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnIDCheck;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnReloadCaptcha;
    private javax.swing.JComboBox<String> cboQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnwer;
    private javax.swing.JLabel lblCaptchaImage;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblPWCheck;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtCaptchaInput;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPW;
    private javax.swing.JPasswordField txtPWConfirm;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
