/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.io.IOException;
/**
 *
 * @author kms03
 */
public class LoginFrame extends javax.swing.JFrame {
    
    DB_MAN DBM = new DB_MAN();
    
    private int failCount = 0;          // 실패 횟수
    private final int MAX_RETRY = 5;    // 기준 횟수
    private String currentCaptchaCode = ""; // 정답 저장용
    
    public LoginFrame() {
        initComponents();
        this.setTitle("시크릿 자산 관리부 - 로그인");
        this.setLocationRelativeTo(null);
        
        pnCaptcha.setVisible(false); // 처음에는 숨기기
        
        this.setSize(400, 300); // 폼 크기 조절
    }
    
    private void setCaptcha() {
        CaptchaGenerator func = new CaptchaGenerator(); 
        
        // 2. 이미지 가져오기 (BufferedImage)
        java.awt.image.BufferedImage img = func.getCaptchaImage();
        
        // 3. JLabel에 이미지를 아이콘으로 변환해서 넣기
        lblCaptchaImg.setIcon(new javax.swing.ImageIcon(img));
        currentCaptchaCode = func.getCaptchaText();
        txtCaptchaKey.setText("");
        System.out.println("캡차 정답: " + currentCaptchaCode);
    }
    
    private void processLoginFailure() {
        failCount++;
        JOptionPane.showMessageDialog(this, "아이디 또는 비밀번호가 일치하지 않습니다.\n(누적 실패: " + failCount + "회)", "로그인 실패", JOptionPane.WARNING_MESSAGE);

        // 실패 횟수가 5회 이상?
        if (failCount >= MAX_RETRY) {
            // 아직 캡차창이 안 떠있다면 띄워줌
            if (!pnCaptcha.isVisible()) {
                JOptionPane.showMessageDialog(this, "로그인 시도가 너무 많습니다.\n보안 문자를 입력해주세요.");
                pnCaptcha.setVisible(true); // 패널 보이기
                setCaptcha();               // 캡차 이미지 생성
                this.setSize(400, 420);     // 폼 크기 조절
            } else {
                // 이미 떠있으면 이미지만 새로고침 
                setCaptcha(); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPW = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        pnCaptcha = new javax.swing.JPanel();
        lblCaptchaImg = new javax.swing.JLabel();
        txtCaptchaKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblTitle.setText("시크릿 자산 관리부");
        lblTitle.setPreferredSize(new java.awt.Dimension(160, 30));

        jLabel2.setText("아이디");

        jLabel3.setText("비밀번호");

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnJoin.setText("회원가입");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        btnFind.setText("비밀번호 찾기");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        lblCaptchaImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("자동 로그인 방지 문자");

        btnRefresh.setText("새로고침");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCaptchaLayout = new javax.swing.GroupLayout(pnCaptcha);
        pnCaptcha.setLayout(pnCaptchaLayout);
        pnCaptchaLayout.setHorizontalGroup(
            pnCaptchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaptchaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtCaptchaKey)
            .addComponent(lblCaptchaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCaptchaLayout.setVerticalGroup(
            pnCaptchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCaptchaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCaptchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaptchaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCaptchaKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin)))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogin)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFind)
                    .addComponent(btnJoin))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String inputId = txtID.getText().trim();
        String inputPw = new String(txtPW.getPassword()); 

        // 입력값 빈칸 검사
        if (inputId.isEmpty() || inputPw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디와 비밀번호를 입력해주세요.", "경고", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 실패 횟수가 5회 이상이면 캡차부터 확인
        if (failCount >= MAX_RETRY) {
            String captchaInput = txtCaptchaKey.getText().trim();
            
            // 입력한 캡차 문자가 정답과 다를 경우
            if (!captchaInput.equals(currentCaptchaCode)) {
                JOptionPane.showMessageDialog(this, "보안 문자가 일치하지 않습니다.", "인증 실패", JOptionPane.WARNING_MESSAGE);
                setCaptcha(); // 보안을 위해 이미지 새로고침
                return; // DB 조회 단계로 넘어가지 않고 종료
            }
        }

        // 비밀번호 조회 쿼리 준비
        String strSQL = "SELECT pw FROM member WHERE id = '" + inputId + "'";

        try {
            DBM.dbOpen(); // DB 연결
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL); // 쿼리 실행

            if (DBM.DB_rs.next()) {
                // ID 존재 시 비밀번호 비교
                String storedPw = DBM.DB_rs.getString("pw");
                
                if (inputPw.equals(storedPw)) {
                    // 로그인 성공
                    JOptionPane.showMessageDialog(this, inputId + "님, 환영합니다!", "로그인 성공", JOptionPane.INFORMATION_MESSAGE);
                    
                    // 실패 횟수 초기화 및 캡차 숨김
                    failCount = 0; 
                    pnCaptcha.setVisible(false);
                    
                    // 메인 화면으로 이동
                    MainFrame mainFrame = new MainFrame(inputId); 
                    mainFrame.setVisible(true); 
                    this.dispose(); // 현재 로그인 창 닫기

                } else {
                    // 비밀번호 불일치
                    processLoginFailure();
                }
            } else {
                // ID 미존재
                processLoginFailure();
            }

            DBM.DB_rs.close(); 
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "DB 연결 초기화 오류가 발생했습니다.", "시스템 오류", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "로그인 처리 중 오류 발생: " + e.getMessage(), "시스템 오류", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                 DBM.dbClose(); // DB 연결 해제
            } catch (IOException e) {
                 e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        JoinFrame joinFrame = new JoinFrame();
        joinFrame.setVisible(true); // 회원가입 창 실행
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        new FindPasswordFrame().setVisible(true); // 비번 찾기 창 실행
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        setCaptcha();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCaptchaImg;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnCaptcha;
    private javax.swing.JTextField txtCaptchaKey;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPW;
    // End of variables declaration//GEN-END:variables
}
